### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Old-Installer#15]
Basically one of the bots on my account detected some issues with pom.xml and I suggest you read the full report and fixing changes [here!](https://github.com/RDIL/Installer/pull/3)

**Comment by Dolphin2Point1** [comment]
Just linking your pull request to your issue. #18

**Comment by RDIL** [comment]
Yeah we’re aware.

**Comment by Cubxity** [comment]
[https://github.com/HyperiumClient/Installer/commit/c468852a3d1ef257c0bacd54a96a2aed0e2666bb](url)
